# -*- coding: utf-8 -*-
"""final15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPRZ1-kY3M13XUUucs8fzuhFmF2IlpGv
"""

"""
เลือกโจทย์: โปรแกรมคำนวณเกรด(A/B/C/D/F)
I: กรอกตัวเลข0-100
P:ตัวเลขตรงกับเงื่อนไขเกรดตัวใหน
O:เกรดที่ได้
ตัวแปร: score
"""

#โปรแกรมคำนวณเกรด(A/B/C/D/F)
# โปรแกรมคำนวณเกรด (A, B, C, D, F)
def calculate_grade():
    try:
        # รับค่าคะแนนจากผู้ใช้
        score = float(input("กรุณากรอกคะแนนของคุณ (0-100): "))

        # ตรวจสอบเงื่อนไขคะแนน
        if score > 100 or score < 0:
            print("ข้อผิดพลาด: กรุณากรอกคะแนนในช่วง 0 ถึง 100 เท่านั้น")
        elif score >= 80:
            print(f"คะแนน {score}: คุณได้เกรด A")
        elif score >= 70:
            print(f"คะแนน {score}: คุณได้เกรด B")
        elif score >= 60:
            print(f"คะแนน {score}: คุณได้เกรด C")
        elif score >= 50:
            print(f"คะแนน {score}: คุณได้เกรด D")
        else:
            print(f"คะแนน {score}: คุณได้เกรด F")

    except ValueError:
        print("ข้อผิดพลาด: กรุณากรอกตัวเลขเท่านั้น")

# เรียกใช้งานฟังก์ชัน
calculate_grade()

import ipywidgets as widgets
from IPython.display import display, clear_output

# --- 1. ฟังก์ชันคำนวณเกรด (ใช้ Logic เดิมของคุณ) ---
def get_grade_logic(score):
    if score > 100 or score < 0:
        return "ข้อผิดพลาด: กรุณากรอกคะแนน 0-100", "danger"
    elif score >= 80:
        return f"คะแนน {score}: คุณได้เกรด A", "success"
    elif score >= 70:
        return f"คะแนน {score}: คุณได้เกรด B", "info"
    elif score >= 60:
        return f"คะแนน {score}: คุณได้เกรด C", "warning"
    elif score >= 50:
        return f"คะแนน {score}: คุณได้เกรด D", "warning"
    else:
        return f"คะแนน {score}: คุณได้เกรด F", "danger"

# --- 2. ส่วนการสร้าง GUI ---
# สร้างช่องกรอกคะแนน
input_box = widgets.FloatText(
    value=0,
    description='คะแนน:',
    style={'description_width': 'initial'}
)

# สร้างปุ่มกด
calc_button = widgets.Button(
    description='คำนวณเกรด',
    button_style='primary', # สีฟ้า
    icon='check'
)

# ส่วนแสดงผลลัพธ์
output_area = widgets.Output()

# --- 3. ฟังก์ชันเมื่อมีการคลิกปุ่ม ---
def on_button_clicked(b):
    with output_area:
        clear_output() # ล้างผลลัพธ์เก่าก่อนแสดงผลใหม่
        result_text, status = get_grade_logic(input_box.value)
        print(result_text)

calc_button.on_click(on_button_clicked)

# --- 4. แสดงหน้าจอโปรแกรม ---
print("=== โปรแกรมคำนวณเกรด (เวอร์ชัน GUI) ===")
display(input_box, calc_button, output_area)