# -*- coding: utf-8 -*-
"""final15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPRZ1-kY3M13XUUucs8fzuhFmF2IlpGv
"""

#โปรแกรมคำนวณเกรด(A/B/C/D/F)
# โปรแกรมคำนวณเกรด (A, B, C, D, F)
def calculate_grade():
    try:
        # รับค่าคะแนนจากผู้ใช้
        score = float(input("กรุณากรอกคะแนนของคุณ (0-100): "))

        # ตรวจสอบเงื่อนไขคะแนน
        if score > 100 or score < 0:
            print("ข้อผิดพลาด: กรุณากรอกคะแนนในช่วง 0 ถึง 100 เท่านั้น")
        elif score >= 80:
            print(f"คะแนน {score}: คุณได้เกรด A")
        elif score >= 70:
            print(f"คะแนน {score}: คุณได้เกรด B")
        elif score >= 60:
            print(f"คะแนน {score}: คุณได้เกรด C")
        elif score >= 50:
            print(f"คะแนน {score}: คุณได้เกรด D")
        else:
            print(f"คะแนน {score}: คุณได้เกรด F")

    except ValueError:
        print("ข้อผิดพลาด: กรุณากรอกตัวเลขเท่านั้น")

# เรียกใช้งานฟังก์ชัน
calculate_grade()